---
- name: Bootstrap server and security rules
  hosts: all
  become: yes
  remote_user: root 

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
        force_apt_get: true

    - name: set wheel group
      group:
        name: wheel
        state: present

    - name: Allow wheel group to be passwordless
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create service account user with sudo priviledges
      ansible.builtin.user:
        name: "{{ lookup('env', 'SERVER_USER') }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash
    
    - name: Set authorized public key for user
      ansible.builtin.authorized_key:
        user: "{{ lookup('env', 'SERVER_USER') }}"
        state: present
        key: "{{ lookup('env', 'SSH_PUBLIC_KEY') }}"

    - name: Disable password authentication for root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: UFW - Enable UFW
      community.general.ufw:
        state: enabled
        policy: allow

    - name: UFW - Allow and change OpenSSH default port
      community.general.ufw:
        rule: limit
        port: "{{ lookup('env', 'SERVER_SSH_PORT') }}"

    - name: UFW - Allow port 80
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: UFW - Allow port 443
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
       
    # A robust solution 
    # See https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible
    - name: Change SSH Port number with lineinfile
      become_user: root
      ansible.builtin.lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: "^Port"
        line: "Port {{ lookup('env', 'SERVER_SSH_PORT') }}"
        backup: true
        owner: root
        group: root
        state: present

    - name: Change Address type
      become_user: root 
      ansible.builtin.lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "AddressFamily"
        line: "AddressFamily inet"
        backup: true
        state: present

 
    - name: Change SSH port number
      become: yes
      become_user: root
      ansible.builtin.shell: |
        SSH_PORT_CONFIG_FILE_PATH=/etc/ssh/sshd_config.d/ssh-port.conf
        
        echo "Port {{ lookup('env', 'SERVER_SSH_PORT') }}\n AddressFamily inet\n" > $SSH_PORT_CONFIG_FILE_PATH 


    # See https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible
    - name: Restart sshd 
      become_user: root
      ansible.builtin.systemd_service:
        name: ssh
        daemon_reload: true
        state: restarted
 
